### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by saviour1108** [pageseeder/schematron#1]
Hi,

I am trying to validate a 250mb xml file using this api, the api runs out of memory even though I've provided 4gigs to it. 

Stacktrace: 
 java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.String.<init>(String.java:201)
	at java.lang.String.substring(String.java:1921)
	at org.pageseeder.schematron.SchematronResult.removeXMLheader(SchematronResult.java:233)
	at org.pageseeder.schematron.SchematronResult.setSVRL(SchematronResult.java:118)
	at org.pageseeder.schematron.Validator.validate(Validator.java:156)

I've had  a look at the code, and the method removeXMLHeader is the place where its running out of memory. Can you please help.

**Comment by clauret** [comment]
Sorry, we had not been watching this repo for a while. This error should no longer occur as there is now an option. no to include the XML declaration in the output instead of trying to remove afterwards.
