### ISSUE TITLE
/org/pageseeder/schematron/xslt/iso_svrl_for_xslt1.xsl' cannot be found in the classpath.

### ISSUE THREAD

**Issue by aarora11** [pageseeder/schematron#2]
Hi, 

Getting the following error when deployed to the server. However I don't see the same error when I'm working locally. Can you help?

java.lang.IllegalArgumentException: preprocessor '/org/pageseeder/schematron/xslt/iso_svrl_for_xslt1.xsl' cannot be found in the classpath.
        at org.pageseeder.schematron.ValidatorFactory.resolvePreprocessor(ValidatorFactory.java:287)
        at org.pageseeder.schematron.ValidatorFactory.resolveDefaultPreprocessor(ValidatorFactory.java:274)
        at org.pageseeder.schematron.ValidatorFactory.<init>(ValidatorFactory.java:136)
        at net.foxopen.fox.plugin.pbsxml.PBSXMLValidationHandler.validateXmlUsingSchematron(PBSXMLValidationHandler.java:438)
        at net.foxopen.fox.plugin.pbsxml.PBSXMLValidationHandler$1.run(PBSXMLValidationHandler.java:81)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-1348" Fox Software Internal Error: Error validating PBS XMLjava.lang.IllegalArgumentException: preprocessor '/org/pageseeder/schematron/xslt/iso_svrl_for_xslt1.xsl' cannot be found in the classpath.

**Comment by clauret** [comment]
My apologies for not seeing this earlier. Just responding in case it is useful to anyone. We've completely refactored the code, and used it standalone and within applications and Web apps without class loading issues.
